stages:
  - test

run_tests:
  stage: test
  image: python:3.8
  before_script:
    - pip install robotframework
  script:
    - robot --outputdir results/ /Autom_RobotFramework
  artifacts:
    paths:
      - results/
  allow_failure: false
